trigger:
- main
pool:
  vmImage: 'windows-latest'
steps:
- task: PowerShell@2
  displayName: Test
  inputs:
    targetType: 'inline'
    script: |
      & sqllocaldb start mssqllocaldb
      dotnet nuget add source '$(DXFeed)' --name DX
      cd $env:BUILD_SOURCESDIRECTORY
      
      dotnet test --configuration TEST
    pwsh: true  