jobs:
  - job: ImportData
    displayName: 'ImportData Job'
    dependsOn: []
    timeoutInMinutes: 90
    variables:
      defaultWorkingDir: '$(System.DefaultWorkingDirectory)\CS'
      runSettingsPath: '$(defaultWorkingDir)\Tests\Tests.runsettings'
      testsFolderPath: '$(defaultWorkingDir)\Tests'
      dxFeedVar: '$(DXFeed)'
      NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
    pool:
        name: Self
    steps:
    - task: PowerShell@2
      displayName: Build
      continueOnError: false
      inputs:
        targetType: 'inline'
        script: |
          & sqllocaldb start mssqllocaldb
          dotnet nuget add source $(dxFeedVar) --name DX

          $projectPath='$(defaultWorkingDir)\Tests\OutlookInspired.Win.Tests\OutlookInspired.Win.Tests.csproj'
          [xml]$xmlDoc = Get-Content $projectPath
          $newPropertyGroup = $xmlDoc.CreateElement("PropertyGroup")
          $defineConstants = $xmlDoc.CreateElement("DefineConstants")
          $defineConstants.InnerText = "TRACE;Import"
          $newPropertyGroup.AppendChild($defineConstants)
          $xmlDoc.Project.AppendChild($newPropertyGroup)
          $xmlDoc.Save($projectPath)

          cd "$(defaultWorkingDir)"
          dotnet build --configuration TEST
          Get-ChildItem -Path "$(testsFolderPath)" -Recurse -Directory -Include "ref", "refint", "obj" | ForEach-Object { Remove-Item $_.FullName -Recurse -Force }  
        pwsh: true      
    - task: VSTest@3
      displayName: 'ImportData.Test'
      continueOnError: false
      enabled: true
      inputs:
        minimumExpectedTests: "1"
        failOnMinTestsNotRun: true
        searchFolder: $(testsFolderPath)
        testSelector: 'testAssemblies'
        testAssemblyVer2: '**\OutlookInspired.Win.Tests.dll'
        testFiltercriteria: TestCategory=ImportData
        diagnosticsEnabled: true
        codeCoverageEnabled: true
        runSettingsFile: $(runSettingsPath)

  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Win.Tests.dll'
      displayName: 'Windows'
  
  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Blazor.Tests.dll'
      displayName: 'Blazor'
