jobs:
  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Win.Tests.dll'
      displayName: 'Windows'
  
  - template: job-template.yml
    parameters:
      testAssembly: '**\OutlookInspired.Blazor.Tests.dll'
      displayName: 'Blazor'
  