trigger:
  - main
pool:
  vmImage: 'windows-latest'
steps:
- task: PowerShell@2
  displayName: Test
  inputs:
    targetType: 'inline'
    script: |
      & sqllocaldb start mssqllocaldb
      dotnet nuget add source '$(DXFeed)' --name DX
      cd $env:BUILD_SOURCESDIRECTORY
      dotnet build --configuration TEST
    pwsh: true  
- task: VSTest@2
  displayName: 'Import'
  inputs:
    searchFolder: '$(System.DefaultWorkingDirectory)\Tests'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.Tests.dll
      !**\obj\**
    testFiltercriteria: FullyQualifiedName=OutlookInspired.Tests.Import.Test
    diagnosticsEnabled: true
    codeCoverageEnabled: true
    runInParallel: false
- task: VSTest@2
  displayName: 'Windows'
  inputs:
    searchFolder: '$(System.DefaultWorkingDirectory)\Tests'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*.Tests.dll
      !**\obj\**
    testFiltercriteria: FullyQualifiedName=OutlookInspired.Tests.Windows.Test
    diagnosticsEnabled: true
    codeCoverageEnabled: true
    runInParallel: false
    