trigger:
- main
pool:
  vmImage: 'windows-2022'
steps:
- task: PowerShell@2
  displayName: Test
  inputs:
    targetType: 'inline'
    script: |
      & sqllocaldb start mssqllocaldb
      dotnet nuget add source '$(DXFeed)' --name DX
      cd $env:BUILD_SOURCESDIRECTORY
      dotnet test --configuration Test
    pwsh: true
# - script: ls D:\a\1\s\Tests\OutlookInspired.Tests\bin\Test\net6.0-windows
  # displayName: 'List bin directory'

# - task: DotNetCoreCLI@2
#   displayName: Test
#   inputs:
#     command: 'test'
#     arguments: '--configuration Test'
    # arguments: '--settings Tests\Tests.runsettings'
  