parameters:
  testAssembly: ''
  displayName: ''

jobs:
- job: ${{ parameters.displayName }}
  variables:
    defaultWorkingDir: '$(System.DefaultWorkingDirectory)\CS'
    runSettingsPath: '$(defaultWorkingDir)\Tests\Tests.runsettings'
    testsFolderPath: '$(defaultWorkingDir)\Tests'
    dxFeedVar: '$(DXFeed)'
    NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  strategy:
    matrix:
      Admin: {}
      Sales: {}
      Support: {}
      Management: {}
      Engineering: {}
      IT: {}
      Shipping: {}
      HumanResources: {}
  timeoutInMinutes: 90
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: PowerShell@2
    displayName: Build
    continueOnError: false
    inputs:
      targetType: 'inline'
      script: |
        Write-Output "${{ parameters.testAssembly }}"
        & sqllocaldb start mssqllocaldb
        dotnet nuget add source $(dxFeedVar) --name DX
        cd "$(defaultWorkingDir)"
        dotnet build --configuration TEST
        Get-ChildItem -Path "$(testsFolderPath)" -Recurse -Directory -Include "ref", "refint", "obj" | 
        ForEach-Object { Remove-Item $_.FullName -Recurse -Force }  
      pwsh: true      
  - task: VSTest@3
    displayName: ${{ parameters.displayName }}
    continueOnError: false
    env:
        TEST_ROLE: $(Agent.JobName)
    enabled: true
    inputs:
      minimumExpectedTests: "1"
      failOnMinTestsNotRun: true
      rerunFailedTests: false
      searchFolder: $(testsFolderPath)
      testSelector: 'testAssemblies'
      testAssemblyVer2: ${{ parameters.testAssembly }}
      testFiltercriteria: TestCategory=Tests
      diagnosticsEnabled: true
      codeCoverageEnabled: true
      uiTests: true
      runSettingsFile: $(runSettingsPath)